### ISSUE TITLE
Swift 3 version?

### ISSUE THREAD

**Issue by Luccifer** [albertodebortoli/Skopelos#8]
Hello! Just wanted to play with CoreData, but xCode can't let me import Swift-Legacy libraries in project... Any news about swift3 version of Skopelos?

**Comment by albertodebortoli** [comment]
Hi @Luccifer I just pushed version 2.0.0 supporting Swift 3.0 (thanks to @keefmoon for the amazing work).
Unfortunately, I didn't succeed in pushing the podspec to truck due to issues, I believe, with Cocoapods. Will do as soon as I find a solution.

**Comment by Luccifer** [comment]
You are my hero! Thanks a lot!

**Comment by albertodebortoli** [comment]
This can now be closed. Version 2.0.0 is on CocoaPods with full Swift 3.0 support.
